# Generated by Django 4.2.26 on 2025-11-19 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketMaster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouriteevent',
            name='date',
        ),
    ]
