# Generated by Django 4.2.26 on 2025-11-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketMaster', '0002_remove_favouriteevent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouriteevent',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='favouriteevent',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
