# Generated by Django 4.2.26 on 2025-11-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketMaster', '0003_favouriteevent_city_favouriteevent_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouriteevent',
            name='date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='favouriteevent',
            name='time',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='favouriteevent',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favouriteevent',
            name='state',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
