# Generated by Django 4.2.26 on 2025-11-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketMaster', '0004_favouriteevent_date_favouriteevent_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouriteevent',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
