# Generated by Django 4.2.26 on 2025-11-29 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketMaster', '0005_favouriteevent_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favouriteevent',
            old_name='image_url',
            new_name='images_url',
        ),
    ]
