# Generated by Django 4.2.26 on 2025-12-01 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TicketMaster', '0006_rename_image_url_favouriteevent_images_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouriteevent',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
